---
include:
  - board: seeeduino_xiao_ble
    shield: eyelash_sofle_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: eyelash_dongle
    cmake-args: -DCONFIG_ZMK_BACKLIGHT=n -DCONFIG_ZMK_RGB_UNDERGLOW=n -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_sofle_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_DISPLAY=n
  - board: eyelash_sofle_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_DISPLAY=n
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: left_reset
  - board: eyelash_sofle_right
    shield: settings_reset
    artifact-name: right_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: dongle_reset
