---
include:
  - board: seeeduino_xiao_ble
    shield: eyelash_sofle_dongle prospector_adapter
    cmake-args: -DCONFIG_ZMK_BACKLIGHT=n
  - board: eyelash_sofle_left
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: eyelash_sofle_right
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  #- board: eyelash_sofle_left
  #  shield: nice_view
  #  snippet: studio-rpc-usb-uart
  #  cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  #  artifact-name: eyelash_sofle_studio_left
  - board: eyelash_sofle_left
    shield: settings_reset
